-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    balance DECIMAL(12,2) DEFAULT 0,
    address VARCHAR(255), 
    password VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    category VARCHAR(510) NOT NULL,
    image BYTEA,
    unit_price DECIMAL(12,2) NOT NULL,
    description VARCHAR(2000)
);

CREATE TABLE Sellers (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY REFERENCES Users(id)
);

CREATE TABLE Inventory (
    sid INT NOT NULL REFERENCES Sellers(id),
    pid INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL,
    PRIMARY KEY(pid)
);

CREATE TABLE Cart (
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Sellers(id),
    quantity INT NOT NULL,
    PRIMARY KEY(uid, pid)
);

CREATE TABLE Later (
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Sellers(id),
    quantity INT NOT NULL,
    PRIMARY KEY(uid, pid)
);

CREATE TABLE RatesSeller (
    uid INT NOT NULL REFERENCES Users(id),
    sid INT NOT NULL REFERENCES Sellers(id),
    rating INT NOT NULL,
    review VARCHAR(2000),
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    image BYTEA,
    PRIMARY KEY(uid, sid, date)
);

CREATE TABLE RatesProduct (
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    rating INT NOT NULL,
    review VARCHAR(2000),
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    image BYTEA,
    PRIMARY KEY(uid, pid, date)
);

CREATE TABLE Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    date_ordered timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    fulfilled BOOL NOT NULL
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    oid INT NOT NULL REFERENCES Orders(id),
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL,
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    unit_price_at_time_of_payment DECIMAL(12,2) NOT NULL,
    fulfilled BOOL NOT NULL
);